project:
  type: website
  preview:
    port: 4200
  output-dir: _docs

format:
  html:
    theme: yeti
    css: styles.css
    highlight-style: pygments
    toc: true
    

website:
  title: ML in classical and quantum physics UIBK W25
  open-graph: true
  site-url: "https://gorkamunoz.github.io/Machine-Learning-Course"
  description: "Machine learning in classical and quantum physics"
  repo-branch: master
  repo-url: "https://github.com/gorkamunoz/Machine-Learning-Course"
  navbar:
    background: '#003361'
    foreground: "#F39200"
    collapse-below: lg
    search: true
    logo: figures/logo.png
  sidebar:
    style: floating

metadata-files: [sidebar.yml]
