project:
  type: website
  preview:
    port: 4200

format:
  html:
    theme: yeti
    css: styles.css
    highlight-style: pygments
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: '#003361'
    foreground: "#F39200"
    collapse-below: lg
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]
