# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/Machine-Learning-Course',
                'doc_host': 'https://gorkamunoz.github.io',
                'git_url': 'https://github.com/gorkamunoz/Machine-Learning-Course',
                'lib_path': 'ml4phys_ibk_w25'},
  'syms': {}}
